let DATA=null;
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(Number(n)||0);
const num=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:0}).format(Number(n)||0);
const pct=n=>new Intl.NumberFormat('en-GB',{style:'percent',maximumFractionDigits:1}).format(Number(n)||0);
const selectedMonthIndex=()=>$('#month').value==='ALL'?-1:DATA.months.indexOf($('#month').value);
const sum=a=>a.reduce((x,y)=>x+(Number(y)||0),0);
const reportYear=()=>Number(DATA.year)||Number(String(DATA.months[0]||'').slice(-2))+2000;
const currentCutoffIndex=()=>{const now=new Date(),year=reportYear();return year<now.getFullYear()?11:year>now.getFullYear()?-1:now.getMonth()};
const includedMonthIndexes=()=>{const selected=selectedMonthIndex();if(selected>=0)return selected<=currentCutoffIndex()?[selected]:[];return DATA.months.map((_,i)=>i).filter(i=>i<=currentCutoffIndex())};
const includedMonths=()=>new Set(includedMonthIndexes().map(i=>DATA.months[i]));
const includesOpenCurrentMonth=()=>{const now=new Date(),cutoff=currentCutoffIndex(),lastDay=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return reportYear()===now.getFullYear()&&now.getDate()<lastDay&&includedMonthIndexes().includes(cutoff)};
function valuesFor(metric){const branch=$('#branch').value;const item=(DATA.pnl[branch]||DATA.pnl['HG ALL']||[]).find(x=>x.metric===metric);if(!item)return[];return includedMonthIndexes().map(i=>item.values[i])}
const normaliseBranch=b=>String(b||'').trim().toUpperCase()==='HG ALL'?'HG ALL':String(b||'').trim();
const normaliseMetric=m=>m==='Non-Fee Earning Customers'?'Non-Fee Earning':m==='HG Staff'?'HG Internal':m;
function warehouseRows(source){const months=includedMonths();let rows=source.filter(r=>months.has(r.month));const b=$('#branch').value;if(b==='HG ALL')rows=rows.filter(r=>normaliseBranch(r.branch)!=='HG ALL');else rows=rows.filter(r=>normaliseBranch(r.branch)===b);return rows.map(r=>({...r,branch:normaliseBranch(r.branch),metric:normaliseMetric(r.metric)}))}
function agg(source){const out={};warehouseRows(source).forEach(r=>{out[r.metric]=(out[r.metric]||0)+r.value});return out}
function card(label,value,sub=''){return `<article class="panel kpi"><span>${label}</span><strong>${value}</strong>${sub?`<small>${sub}</small>`:''}</article>`}
function renderSummary(){
 const revenue=sum(valuesFor('Total Storage Revenue')), costs=sum(valuesFor('Total Property Costs')), external=sum(valuesFor('3rd Party Warehousing - Direct')), gp=sum(valuesFor('Gross Storage Profit')), margin=revenue?gp/revenue:0;
 $('#headline').innerHTML=card('Storage revenue',money(revenue))+card('Total property costs',money(costs))+card('Gross storage profit',money(gp))+card('Gross margin',pct(margin));
 const items=(DATA.pnl[$('#branch').value]||DATA.pnl['HG ALL']||[]).filter(x=>x.metric!=='Gross Margin %');const monthIndexes=includedMonthIndexes();
 $('#pnl-table').innerHTML='<thead><tr><th>Metric</th><th class="num">Value</th><th class="num">% of revenue</th></tr></thead><tbody>'+items.map(x=>{const v=sum(monthIndexes.map(i=>x.values[i]));const total=/Gross Storage Profit|Total Property Costs/.test(x.metric);return `<tr class="${total?'total':''}"><td>${x.metric}</td><td class="num">${money(v)}</td><td class="num">${revenue?pct(v/revenue):'—'}</td></tr>`}).join('')+'</tbody>';
 $('#summary-period').textContent=$('#month').value==='ALL'?`${reportYear()} year to date (to ${DATA.months[currentCutoffIndex()]})`:$('#month').value;
 const w=agg(DATA.warehouse), ex=agg(DATA.external);const months=selectedMonthIndex()<0?new Set(warehouseRows(DATA.warehouse).map(x=>x.month)).size:1;const capRows=warehouseRows(DATA.warehouse).filter(x=>x.metric==='Fee Earning');const capacityPerPeriod=[...new Map(capRows.map(r=>[r.branch,r.capacity])).values()].reduce((a,b)=>a+b,0);const total=(w['Fee Earning']||0)+(w['Non-Fee Earning']||0);const util=capacityPerPeriod&&months?total/(capacityPerPeriod*months):0;
 $('#warehouse-cards').innerHTML=card('Warehouse capacity',num(capacityPerPeriod),'Available wooden capacity')+card('Fee earning',num(w['Fee Earning']))+card('Non-fee earning',num(w['Non-Fee Earning']))+card('Total utilisation',pct(util));
 const rows=[['Fee Earning',w['Fee Earning']],['Non-Fee Earning',w['Non-Fee Earning']],['HG Resale',w['HG Resale']],['HG Internal',w['HG Internal']],['Empty Woodens',w['Empty Woodens']],['External Fee Earning',ex['Fee Earning']],['External Non-Fee Earning',ex['Non-Fee Earning']]];
 $('#summary-warehouse-table').innerHTML='<thead><tr><th>Measure</th><th class="num">Number</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${r[0]}</td><td class="num">${num(r[1])}</td></tr>`).join('')+'</tbody>';
}
function renderContainers(){let rows=DATA.containers.filter(r=>includedMonths().has(r.month));if($('#branch').value!=='HG ALL')rows=rows.filter(r=>r.branch===$('#branch').value);$('#container-table').innerHTML='<thead><tr><th>Month</th><th>Branch</th><th class="num">Capacity</th><th class="num">Woodens</th><th class="num">In use</th><th class="num">Empty</th><th class="num">Wooden util.</th><th class="num">Space available</th><th class="num">Space util.</th><th class="num">External woodens</th><th class="num">External pallets</th><th class="num">Steel onsite</th><th class="num">External steel</th><th class="num">Headcount</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${r.month}</td><td>${r.branch}</td><td class="num">${num(r.capacity)}</td><td class="num">${num(r.woodenNumbers)}</td><td class="num">${num(r.woodensInUse)}</td><td class="num">${num(r.emptyWoodens)}</td><td class="num">${pct(r.woodenUtilisation)}</td><td class="num">${num(r.spaceAvailable)}</td><td class="num">${pct(r.spaceUtilisation)}</td><td class="num">${num(r.externalWoodens)}</td><td class="num">${num(r.externalPallets)}</td><td class="num">${num(r.steelOnsite)}</td><td class="num">${num(r.externalSteel)}</td><td class="num">${num(r.headcount)}</td></tr>`).join('')+'</tbody>'}
function renderMeasureTable(id,source){const metricOrder=[...new Set(source.map(r=>r.metric))];const rows=warehouseRows(source).sort((a,b)=>DATA.months.indexOf(a.month)-DATA.months.indexOf(b.month)||metricOrder.indexOf(a.metric)-metricOrder.indexOf(b.metric)||a.branch.localeCompare(b.branch));let previousMonth='',previousMeasure='';$('#'+id).innerHTML='<thead><tr><th>Month</th><th>Measure</th><th>Branch</th><th class="num">Capacity</th><th class="num">Number</th></tr></thead><tbody>'+rows.map(r=>{const month=r.month===previousMonth?'':r.month;const measureKey=`${r.month}|${r.metric}`;const measure=measureKey===previousMeasure?'':r.metric;previousMonth=r.month;previousMeasure=measureKey;return `<tr class="${month?'month-start':measure?'measure-start':''}"><td>${month}</td><td>${measure}</td><td>${r.branch}</td><td class="num">${num(r.capacity)}</td><td class="num">${num(r.value)}</td></tr>`}).join('')+'</tbody>'}
function render(){renderSummary();renderContainers();renderMeasureTable('warehouse-table',DATA.warehouse);renderMeasureTable('external-table',DATA.external);$('#scope-label').textContent=`${$('#branch').value} · ${$('#month').value==='ALL'?`${reportYear()} YTD`:$('#month').value}`;const note=$('#current-period-note');note.textContent=`${DATA.months[currentCutoffIndex()]} is still in progress, so figures including this month are subject to change.`;note.classList.toggle('hidden',!includesOpenCurrentMonth())}
function setup(){DATA.branches.forEach(b=>$('#branch').add(new Option(b,b)));$('#branch').value='HG ALL';$('#month').add(new Option('Year to date','ALL'));DATA.months.filter((_,i)=>i<=currentCutoffIndex()).forEach(m=>$('#month').add(new Option(m,m)));$('#branch').addEventListener('change',render);$('#month').addEventListener('change',render);$('#reset').addEventListener('click',()=>{$('#branch').value='HG ALL';$('#month').value='ALL';render()});document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active')}));$('#updated').textContent=`Updated ${new Date(DATA.generatedAt).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}`;render()}
fetch('dashboard-data.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Dashboard data could not be loaded.');return r.json()}).then(d=>{DATA=d;setup()}).catch(e=>{$('#error').textContent=e.message;$('#error').classList.remove('hidden');$('#updated').textContent='Data unavailable'});
